### ISSUE TITLE
IE 10 issue

### ISSUE THREAD

**Issue by joshuaLareta** [javascriptiscoolpl/npm-simple-react-pdf#7]
This works well with other browser except IE10.

Shows `unhandled promise rejection` with an object of `access denied`

Any work around for this issue?

**Comment by javascriptiscoolpl** [comment]
I don't have IE10. I use Ubuntu with Firefox, Chrome and Opera. I have gaming PC machine with Windows 8.1 too but I am not sure what kind of IE version is there. 

Are you sure this is code IE browser support issue? not env or something else? This pdf read method is according to the pdf.js documentation so this should work under other browsers as well, I guess. I will try to find IE somewhere and find out what is going on. However, This may require fake node installation on Windows. May I ask how did You tested on Windows with IE10? I will try to reproduce it then.

Thanks for this issue, I will leave it open until I find IE10 and test it in similar environment.

**Comment by javascriptiscoolpl** [comment]
I have just seen that IE might be partially supported. So there might be problem with the library itself. 
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

However, I will be trying to reproduce it, probably this week.

**Comment by joshuaLareta** [comment]
@javascriptiscoolpl Thanks for the fast response. 

I have a window machine which I use to test for IE10 and Edge. Been researching on PDF.js as well. it seems to be an issue on the data I was passing, as I was using a base64 encoded pdf data and it seems that IE does not want that.

**Comment by javascriptiscoolpl** [comment]
Oh, OK. For base64 there must be decoding part so this should not work also under other browsers, I guess. Did You tested it under Firefox or any other browser as well? Maybe I should add something for encoded pdfs as well, option or something automatic better to keep it simple to use. 

Maybe more details about the window with IE machine? This is wine? or this is any kind of platform simulator?

**Comment by joshuaLareta** [comment]
simplePdf actually works fine with other browser whether it be url or base64 data. Will update you about the window machine details. currently we have a dev environment which we can publicly access over intranet to test out with windows IE. 

My current machine is a macOS sierra, tested it on Firefox, chrome and safari.

**Comment by javascriptiscoolpl** [comment]
I don't have macOS too but system should not be a problem if the node environment is correctly installed, I guess. Good to know that base64 works as well. As I remember there are problems in case of advanced pdf documents, like special fonts or something with localization. 

Nice to hear You can share the access to the reproduce lab. Can't wait. Thanks.

**Comment by javascriptiscoolpl** [comment]
By the way I make small research regarding the error message `unhandled promise rejection` and `access denied` and this all go into security issue direction strictly related to the **CORS (Cross-Origin Resource Sharing)**. You can also make more research on that.

**Comment by joshuaLareta** [comment]
manage to display the pdf by converting base64 data to uint8Array. Problem now is in simplePDF `node.clientWidth` returns 0 on the first page then will have a proper clientWidth on the second page.

**Comment by javascriptiscoolpl** [comment]
Nice to hear it starting to work. If now the problem is with `width`, You probably have to define `.SimplePDF` class with `width` and `height`. The pdf canvas automatically adjust the size to the box container of `.SimplePDF` class. This use box model. There are no defaults for `width` and `height`. Just define somewhere the CSS rule: 
```
.SimplePDF {
  width: 350px;
  height: 500px;
}
```
See `Readme` or `index.html` example for more details in demo folder. 

However, I will leave this issue open and will try to test this module on Windows under IE (don't know what version IE I have there). Because this module has never been tested under the Windows and IE, so I have no idea if this works there or not, in fact.

**Comment by javascriptiscoolpl** [comment]
I have just tested this on my PC gaming machine under Windows 8.1. There is IE11+ version and I was able to reproduce the error message.

I can confirm there is security IE issue probably described here:
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr
https://www.webdavsystem.com/ajax/programming/cross_origin_requests

This issue is related to IE only, because on the same machine Firefox loaded the demo `index.html` file without any problems. 

I will leave this issue open for some time. I need to rethink if the code changes are needed.

**Comment by javascriptiscoolpl** [comment]
There is currently CORS security issue also in google-chrome and opera. Probably they released new CORS feature there. So, I decided to create new example with server-client idea:

**simple-react-pdf-service**: https://www.npmjs.com/package/simple-react-pdf-service

Also we can wait what Mozilla will do with it, because now only Firefox support it. However, when client through JavaScript is starting to read the filesystem there is always confusion around :-)

I am going to close this issue, if there will not be more comments. 
Feel free to re-open or create new issue.
